### ISSUE TITLE
Passcode entry screen plays two vibrations for mismatched fingerprints

### ISSUE THREAD

**Issue by AppleBetas** [Sticktron/LockGlyphX#29] opened 2017-02-23 19:13 UTC
Because stock iOS now plays a vibration for incorrect passcode, we should disable the LockGlyphX provided one while the passcode view is shown.

**Comment by Sticktron** [comment] 2017-02-26 00:38
Do you know if that's new in 10.2, or does it apply to all versions of 10?

**Comment by Sticktron** [comment] 2017-02-27 04:09
I can't reproduce this.

**Comment by AppleBetas** [comment] 2017-02-27 04:09
I experienced it the iOS 10.0 betas as well, and am able to get it to happen on another pre-haptic engine device.

**Comment by Sticktron** [comment] 2017-02-27 04:10
ah so it only affects those?

**Comment by AppleBetas** [comment] 2017-02-27 04:11
I'm not quite sure, but I don't have any devices later than the 6 to test it on.

**Comment by AppleBetas** [comment] 2017-02-27 04:11
Does your phone vibrate when the passcode dots get filled, or when the lock in the status bar vibrates? (the status bar lock vibrating is at the same time as the stock vibration)

**Comment by Sticktron** [comment] 2017-02-27 04:11
It makes a gentle buzz

**Comment by Sticktron** [comment] 2017-02-27 04:12
Not the same vibration that LockGlyph makes

**Comment by AppleBetas** [comment] 2017-02-27 04:13
If its not playing the LockGlyph vibration already while in the passcode screen, adding a check for the passcode screen for the LockGlyph vibration would be harmless

**Comment by Sticktron** [comment] 2017-02-27 04:21
ok, I added said check. closing.

**Closed as completed by Sticktron** 2017-02-27 04:21 UTC
Labels: bug
